// Mocks generated by Mockito 5.4.6 from annotations
// in yansnet/test/feature_verification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yansnet/features/auth/domain/auth_domain.dart' as _i2;
import 'package:yansnet/features/auth/domain/usecases/login_usecase.dart'
    as _i9;
import 'package:yansnet/features/chat/domain/entities/conversation_entity.dart'
    as _i8;
import 'package:yansnet/features/chat/domain/entities/message_entity.dart'
    as _i7;
import 'package:yansnet/features/chat/domain/repositories/chat_repository.dart'
    as _i6;
import 'package:yansnet/features/chat/domain/usecases/get_conversations_usecase.dart'
    as _i18;
import 'package:yansnet/features/chat/domain/usecases/get_messages_usecase.dart'
    as _i19;
import 'package:yansnet/features/chat/domain/usecases/send_message_usecase.dart'
    as _i20;
import 'package:yansnet/features/chat/domain/usecases/start_chat_usecase.dart'
    as _i21;
import 'package:yansnet/features/events/domain/entities/event_entity.dart'
    as _i15;
import 'package:yansnet/features/events/domain/repositories/event_repository.dart'
    as _i5;
import 'package:yansnet/features/events/domain/usecases/cancel_rsvp_usecase.dart'
    as _i17;
import 'package:yansnet/features/events/domain/usecases/get_events_usecase.dart'
    as _i14;
import 'package:yansnet/features/events/domain/usecases/rsvp_event_usecase.dart'
    as _i16;
import 'package:yansnet/features/posts/domain/entities/post_entity.dart' as _i4;
import 'package:yansnet/features/posts/domain/repositories/post_repository.dart'
    as _i3;
import 'package:yansnet/features/posts/domain/usecases/create_post_usecase.dart'
    as _i12;
import 'package:yansnet/features/posts/domain/usecases/get_posts_usecase.dart'
    as _i11;
import 'package:yansnet/features/posts/domain/usecases/like_post_usecase.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostRepository_2 extends _i1.SmartFake
    implements _i3.PostRepository {
  _FakePostRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePost_3 extends _i1.SmartFake implements _i4.Post {
  _FakePost_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventRepository_4 extends _i1.SmartFake
    implements _i5.EventRepository {
  _FakeEventRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRepository_5 extends _i1.SmartFake
    implements _i6.ChatRepository {
  _FakeChatRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_6 extends _i1.SmartFake implements _i7.Message {
  _FakeMessage_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversation_7 extends _i1.SmartFake implements _i8.Conversation {
  _FakeConversation_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i9.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i10.Future<_i2.AuthResponse> call(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password]),
            returnValue: _i10.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#call, [email, password]),
              ),
            ),
          )
          as _i10.Future<_i2.AuthResponse>);
}

/// A class which mocks [GetPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPostsUseCase extends _i1.Mock implements _i11.GetPostsUseCase {
  MockGetPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PostRepository);

  @override
  _i10.Future<List<_i4.Post>> call({int? page = 0, int? size = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #size: size}),
            returnValue: _i10.Future<List<_i4.Post>>.value(<_i4.Post>[]),
          )
          as _i10.Future<List<_i4.Post>>);
}

/// A class which mocks [CreatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePostUseCase extends _i1.Mock implements _i12.CreatePostUseCase {
  MockCreatePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PostRepository);

  @override
  _i10.Future<_i4.Post> call(String? content, {List<String>? mediaPaths}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [content], {#mediaPaths: mediaPaths}),
            returnValue: _i10.Future<_i4.Post>.value(
              _FakePost_3(
                this,
                Invocation.method(#call, [content], {#mediaPaths: mediaPaths}),
              ),
            ),
          )
          as _i10.Future<_i4.Post>);
}

/// A class which mocks [LikePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikePostUseCase extends _i1.Mock implements _i13.LikePostUseCase {
  MockLikePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PostRepository);

  @override
  _i10.Future<void> call(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [postId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [GetEventsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEventsUseCase extends _i1.Mock implements _i14.GetEventsUseCase {
  MockGetEventsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.EventRepository);

  @override
  _i10.Future<List<_i15.Event>> call({int? page = 0, int? size = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #size: size}),
            returnValue: _i10.Future<List<_i15.Event>>.value(<_i15.Event>[]),
          )
          as _i10.Future<List<_i15.Event>>);
}

/// A class which mocks [RsvpEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRsvpEventUseCase extends _i1.Mock implements _i16.RsvpEventUseCase {
  MockRsvpEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.EventRepository);

  @override
  _i10.Future<void> call(int? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [eventId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [CancelRsvpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelRsvpUseCase extends _i1.Mock implements _i17.CancelRsvpUseCase {
  MockCancelRsvpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.EventRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEventRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.EventRepository);

  @override
  _i10.Future<void> call(int? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [eventId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [GetConversationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationsUseCase extends _i1.Mock
    implements _i18.GetConversationsUseCase {
  MockGetConversationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.ChatRepository);

  @override
  _i10.Future<List<_i8.Conversation>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i10.Future<List<_i8.Conversation>>.value(
              <_i8.Conversation>[],
            ),
          )
          as _i10.Future<List<_i8.Conversation>>);
}

/// A class which mocks [GetMessagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessagesUseCase extends _i1.Mock
    implements _i19.GetMessagesUseCase {
  MockGetMessagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.ChatRepository);

  @override
  _i10.Future<List<_i7.Message>> call(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversationId]),
            returnValue: _i10.Future<List<_i7.Message>>.value(<_i7.Message>[]),
          )
          as _i10.Future<List<_i7.Message>>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i20.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.ChatRepository);

  @override
  _i10.Future<_i7.Message> call(int? conversationId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversationId, content]),
            returnValue: _i10.Future<_i7.Message>.value(
              _FakeMessage_6(
                this,
                Invocation.method(#call, [conversationId, content]),
              ),
            ),
          )
          as _i10.Future<_i7.Message>);
}

/// A class which mocks [StartChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartChatUseCase extends _i1.Mock implements _i21.StartChatUseCase {
  MockStartChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.ChatRepository);

  @override
  _i10.Future<_i8.Conversation> call(int? otherUserId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [otherUserId]),
            returnValue: _i10.Future<_i8.Conversation>.value(
              _FakeConversation_7(
                this,
                Invocation.method(#call, [otherUserId]),
              ),
            ),
          )
          as _i10.Future<_i8.Conversation>);
}
